// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_10_stars_achieved = "CgkIrLeZ6ecMEAIQDA"; // <GPGSID>
        public const string achievement_20_stars_achieved = "CgkIrLeZ6ecMEAIQBA"; // <GPGSID>
        public const string achievement_40_stars_achieved = "CgkIrLeZ6ecMEAIQBg"; // <GPGSID>
        public const string achievement_70_stars_achieved = "CgkIrLeZ6ecMEAIQCQ"; // <GPGSID>
        public const string achievement_50_stars_achieved = "CgkIrLeZ6ecMEAIQBw"; // <GPGSID>
        public const string achievement_30_stars_achieved = "CgkIrLeZ6ecMEAIQBQ"; // <GPGSID>
        public const string achievement_60_stars_achieved = "CgkIrLeZ6ecMEAIQCA"; // <GPGSID>
        public const string achievement_90_stars_achieved = "CgkIrLeZ6ecMEAIQCw"; // <GPGSID>
        public const string achievement_80_stars_achieved = "CgkIrLeZ6ecMEAIQCg"; // <GPGSID>

}

